### ISSUE TITLE
Sturdy sheet item from Create is uncraftable

### ISSUE THREAD

**Issue by tdepke2** [TqLxQuanZ/DeceasedCraft#2]
The Sturdy Sheet item uses Create's sequenced assembly and is crafted by first pouring lava on powdered obsidian. The crafttweaker recipe added for minecraft:ender_pearl also starts with this step, and seems to always take priority. I don't know of a way to configure the sequenced assembly to select between these two recipes unless I missed something.

It should be an easy fix to update `scripts/item.zs` and have the ender pearl crafted from water first, then lava, or something like that.

I'm using `DeceasedCraft_Client_v3.1.4` but didn't see a fix for this in later releases, feel free to close if this was fixed already.

**Comment by TqLxQuanZ** [comment]
Hi, thanks for the reporting, this issue has been fixed in 3.2.0 version but not yet released due to the armor set bonus mod haven't updated to latest yet, please be patient and wait for it.

**Comment by tdepke2** [comment]
Ah, I see your commit b970a8e that addresses this. I think I tried changing the ender pearl recipe to start with water first and the sturdy sheet was still not craftable, but it's possible I forgot to reload the configs in my testing.

**Comment by TqLxQuanZ** [comment]
@tdepke2  Hey sorry for the late update, 3.2.0 is here, please do update it to fix all the recipe issues!
